name: voici
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - xeus-python
  - mock
  - pandas
  - numpy
  - bqplot
  - reacton
  - ipyvuetify
  - markdown
  - pymdown-extensions
  - solara-ui
  - dyno
  - dolang
  - scipy
  - plotly
